RESOPS27 - Set up ci for the listings service
UVicMartletplace/martletplace pull request #102
Opened 2024-06-02 22:46 UTC by TobySMurray

# Description

Create the base CI jobs for the Listingservice: linting, formatting, testing, and security

This PR is stacked on top of #83, so first review that PR (as this diff contains that PR diff also).

Closes #27 

## How to Test

View the CI output below or run the actions locally with [act](https://github.com/nektos/act)

## Checklist
- [x] The code includes tests if relevant
- [x] I have *actually* self-reviewed my changes and done QA

2024-06-03 22:59 UTC, kylestang requested changes
Looks good except I don't think we want to be removing the search service config

2024-06-03 22:59 UTC, kylestang commented on .github/workflows/search.yml
Do we want to be deleting this?

2024-06-03 22:59 UTC, kylestang commented on docker-compose.yml
This is replacing the search service in the docker compose. Don't we want to add the listing service alongside it?

2024-06-05 00:12 UTC, Scott-Kenning approved these changes

2024-06-05 00:12 UTC, kylestang approved these changes
LGTM

2024-06-05 00:12 UTC, merged