Frontend changes for user auth + user context (storing the user)
UVicMartletplace/martletplace pull request #208
Opened 2024-06-24 08:25 UTC by Scott-Kenning

# Description
Frontend changes for user auth, + storing user in context

Closes #90

## How to Test
Run, create account, login, navigate to profile page

## Checklist
- [x] The code includes tests if relevant
- [x] I have *actually* self-reviewed my changes and done QA

2024-06-24 18:37 UTC, CaelumD25 approved these changes
It looks okay to me, but the tests do need to be passing before merging. As long as that works I'm happy with this

2024-06-24 21:34 UTC, MNThomson requested changes
Not sure why there is anything related to cookies in this pr. The front-end physically (I guess virtually???) cannot access the auth cookie/token

2024-06-24 21:34 UTC, MNThomson commented on apps/frontend/src/_axios_instance.tsx
> +  baseURL: "http://localhost/api/", // Your custom base URL
This should be whatever hostname is in the url bar

2024-06-24 21:34 UTC, MNThomson commented on apps/frontend/src/contexts/UserProvider.tsx
> +    Cookies.remove("token");
Front-end will not have any access to the token. It's not being sent in the http response body. It's in a `Set-Cookie` header that has `httponly = true` meaning that the front-end CANNOT read (not that you shouldn't, but that the browser will not give it to you)

2024-06-25 22:58 UTC, MNThomson approved these changes

2024-06-25 23:00 UTC, islandj123 approved these changes
tis code

2024-06-25 23:01 UTC, merged